# Generated by Django 5.0 on 2023-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
