# Generated by Django 5.0 on 2023-12-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='banner2',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
